# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: kaminari-i18n 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "kaminari-i18n"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Christopher Dell"]
  s.date = "2014-07-29"
  s.description = "Translations for the kaminari gem"
  s.email = "chris@tigrish.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "kaminari-i18n.gemspec",
    "lib/kaminari-i18n.rb",
    "locales/az.yml",
    "locales/de.yml",
    "locales/en.yml",
    "locales/es.yml",
    "locales/fi.yml",
    "locales/fr.yml",
    "locales/it.yml",
    "locales/ja.yml",
    "locales/ko.yml",
    "locales/pl.yml",
    "locales/pt-BR.yml",
    "locales/ru.yml",
    "locales/sk.yml",
    "locales/zh.yml",
    "spec/kaminari-i18n_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/tigrish/kaminari-i18n"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Translations for the kaminari gem"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<localeapp>, [">= 0"])
      s.add_development_dependency(%q<rails>, [">= 0"])
      s.add_development_dependency(%q<i18n-spec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<localeapp>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<i18n-spec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<localeapp>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<i18n-spec>, [">= 0"])
  end
end

